### ISSUE TITLE
Add support for extracting from HTML files

### ISSUE THREAD

**Issue by PPPDUD** [TurboWarp/unpackager#1]
I could use this for my OLD project, JanaOS, which can only be found in HTML.

**Comment by GarboMuffin** [comment]
HTML files should already be supported

**Comment by GarboMuffin** [comment]
How old is your file? Old ones probably won't work yet

**Comment by PPPDUD** [comment]
Pretty old. Thanks for telling me.

**Comment by GarboMuffin** [comment]
Support for older versions of the packagers have been added so you should be able to just select the HTML file and get the project out.

If not, post the project here or to contact@turbowarp.org and I'll make it work

**Comment by PPPDUD** [comment]
Excellent!

**Comment by PPPDUD** [comment]
Thanks.
