### ISSUE TITLE
Custom stage size not automatically preserved

### ISSUE THREAD

**Issue by TotalTaco** [TurboWarp/unpackager#2]
Custom resolutions dont get exported in the proper resolution.

**Comment by GarboMuffin** [comment]
comments are not the problem

**Comment by TotalTaco** [comment]
I'm going to try and code my way to fixing this issue, hopefully my code works, lol.

**Comment by GarboMuffin** [comment]
I am more than happy just getting the project files back out. Applying settings is something you can do manually, we don't need to add support here and make it more complicated than it already is. The main use for the unpackager anyways is data recovery
