### ISSUE TITLE
Disable unpacking

### ISSUE THREAD

**Issue by HangingWithCMM** [TurboWarp/unpackager#4]
There should be a way that disables unpacking permanently for that game.

**Comment by GarboMuffin** [comment]
There are no reasonable technical measures that would actually prevent people from getting something close to the original sb3 from your packaged project. Note that even without the unpackager, getting the original sb3 is still extremely trivial (the data is literally just sitting in the HTML file or zip!)

You can enforce control over your project through the legal system (copyright claims etc.) if you feel the need.

**Comment by GarboMuffin** [comment]
Even if we did add a "prevent unpackaging" option that encoded the project in some way and didn't add support for to the unpackager, someone else would do that for us. We are 100% open source here, after all.

**Comment by GarboMuffin** [comment]
We, as volunteers developing open source software, will not be providing this. You are welcome to find another solution, however you are entirely on your own there. Do keep in mind that billion dollar video game development companies spend a lot of money on DRM and anti-cheat software and that are anything but perfect.

**Comment by GarboMuffin** [comment]
If you are worried about cheating -> unpackaging and repackaging a project is one of the slowest ways to cheat cloud variables. There are so many others ways to cheat.

If you are worried about people stealing your project -> they can already just share your files. At some point all of your assets must be decrypted to be rendered by Scratch, so they will always be able to grab them then. There are legal systems for fighting unauthorized use of your work.

If you are selling your project for real money -> you should be able to find someone to help you further if you are serious about making money

**Comment by GarboMuffin** [comment]
No

**Comment by GarboMuffin** [comment]
You could try to implement DRM in an extension. But someone could simply comment out that code. See previous comments.

**Comment by GarboMuffin** [comment]
You are on your own. Please refer to my previous comment: https://github.com/TurboWarp/unpackager/issues/4#issuecomment-1522838418

**Comment by J4ol** [comment]
> @GarboMuffin yes but some protection is better than none. How would I implement an extension like that?
I made something called "Codebomb"

**Comment by J4ol** [comment]
Send Me Your .sb3 File and Send The Packing Config, And I will Codebomb It (Ant-unpacking) After Codebombing it will crash scratch if it is loaded

**Comment by J4ol** [comment]
Yep Give me a min

**Comment by J4ol** [comment]
Sorry It takes a while, It has like 25 Different Sprites

**Comment by J4ol** [comment]
Ok Done

**Comment by J4ol** [comment]
1. Add This Code To Your Project


When green flag clicked
Forever
REST TIMER

**Comment by J4ol** [comment]
Did you add the code

**Comment by J4ol** [comment]
nope

**Comment by J4ol** [comment]
https://drive.google.com/drive/folders/1Mi7yb9dW2dMlcygeLjXaKQK1RrN-IHl3?usp=sharing
Press The Green Flag Then Import All The Code Bomb Files At Once

**Comment by J4ol** [comment]
There is one more step

**Comment by J4ol** [comment]
BY THE WAY BACKUP THE PRJECT BEFORE IMPORT!

**Comment by J4ol** [comment]
Nope and 1 more step close the project and follow this YT video: https://www.youtube.com/watch?v=2HbiAz2fnm8 and then it is ready for packing

**Comment by J4ol** [comment]
Yeah, But it is a small thing that helps. Try opening the project now on your editor

**Comment by J4ol** [comment]
hello?

**Comment by J4ol** [comment]
Are you still here?

**Comment by J4ol** [comment]
Ok lets delete all of our comments

**Comment by J4ol** [comment]
You know couse I dont want codebomb to leak

**Comment by J4ol** [comment]
Im Now Coding A Anit Unpacker
