### ISSUE TITLE
Can it prevent unpacking by importing third-party extensions

### ISSUE THREAD

**Issue by qxsck** [TurboWarp/unpackager#5]
.

**Comment by GarboMuffin** [comment]
At this time the unpackager may or may not support extensions (may depend how they get loaded), so possibly. But in principal, custom extension do not change that projects fundamentally can be extracted from the generated files.

**Comment by qxsck** [comment]
> At this time the unpackager may or may not support extensions (may depend how they get loaded), so possibly. But in principal, custom extension do not change that projects fundamentally can be extracted from the generated files.

thanks

**Comment by PSYclownYT** [comment]
extensions work 100%
