### ISSUE TITLE
Standalone HTML files don't extract.

### ISSUE THREAD

**Issue by SuperSonic472** [TurboWarp/unpackager#8]
I'm trying to preserve a old sonic game and the only remnant left is a standalone [HTML](https://files.catbox.moe/9ibhik.html) file. (Thanks [catbox](https://catbox.moe/) for the free download link!) It allows standalone HTML files to be uploaded, but it gives a error saying "Input was not a zip and we could not find project." If you could allow for HTML decompiling then that would be useful. Thanks! ^_^

**Comment by GarboMuffin** [comment]
should be fixed soon
